// <auto-generated />
namespace Elysium.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class RelationUpdates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RelationUpdates));
        
        string IMigrationMetadata.Id
        {
            get { return "202002021501485_RelationUpdates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
